server:
  port: 8090
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/project_kafka?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&&serverTimezone=UTC
    username: ENC(m9oQEfoMqnSxjNe45c8u5w==)
    password: ENC(6DXWFIbXQ6ZJ6L+eKoPd0FzzI6s+2YVw)
  liquibase:
    change-log: /db/changelog/changelog-master.xml
    enabled: true
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      ddl-auto: validate
    show-sql: true

jasypt:
  encryptor:
    bean: encryptorBean
